default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: rails_friend_online_making_01_development

test:
  <<: *default
  database: rails_friend_online_making_01_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
